# docker-compose.yml
services:
  bom-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - STREAMLIT_SERVER_PORT=${STREAMLIT_SERVER_PORT}
        - STREAMLIT_SERVER_ADDRESS=${STREAMLIT_SERVER_ADDRESS}
    container_name: bom-app
    ports:
      - "${STREAMLIT_SERVER_PORT}:8501"
    environment:
      - DUCKDB_PATH=/app/data/bom.duckdb
      - STREAMLIT_SERVER_PORT=${STREAMLIT_SERVER_PORT}
      - STREAMLIT_SERVER_ADDRESS=${STREAMLIT_SERVER_ADDRESS}
      - STREAMLIT_SERVER_ENABLE_CORS=false
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_MAX_MESSAGE_SIZE=2000000
    volumes:
      - ./data:/app/data
      - ./app:/app/app